version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - MYSQL_ROOT_PASSWORD: PuPKcCKfxzw6bxUl
      - MYSQL_DATABASE: django
      - MYSQL_USER: django
      - MYSQL_PASSWORD: 36HgLBcQwRdUuAgj
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db