version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - MYSQL_ROOT_PASSWORD=PuPKcCKfxzw6bxUl
      - MYSQL_DATABASE=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=36HgLBcQwRdUuAgj
  web:
    build: .
    command: sh -c "./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8013"
    volumes:
      - .:/code
    ports:
      - "8013:8013"
    depends_on:
      - db
